#!/usr/bin/env python3
"""Regenerate paper/submission/ from paper/main.tex (the single source of truth).

ARR requires an anonymized, line-numbered copy in the ACL template. Instead of
hand-maintaining a second .tex, derive it mechanically:

  * \\usepackage[final]{acl}  ->  \\usepackage[review]{acl}
        (acl.sty's review option = anonymous authors + line numbers + page
        numbers, which is exactly what ARR asks for)
  * the author block          ->  "Anonymous submission"
  * the public-repo footnote  ->  the anonymized-release sentence
  * everything else, including \\bibliography{references}, copied verbatim

The previous hand-written copy had drifted: it dropped acl.sty for
fontspec/geometry (no line numbers, wrong template) and replaced the .bib with
a hand-typed thebibliography containing misattributed entries. Do not edit
paper/submission/main.tex by hand — edit paper/main.tex and re-run this.

    python scripts/make_submission.py            # regenerate (+ compile if possible)
    python scripts/make_submission.py --no-build # regenerate only
"""

import os
import re
import shutil
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
PAPER = os.path.join(ROOT, "paper")
SUB = os.path.join(PAPER, "submission")

ANON_FOOTNOTE = ("Code, logs, and the full reproduction pipeline are "
                 "anonymized for review and will be released upon acceptance.")

REPO_URL_RE = re.compile(r"\\footnote\{\\url\{https://github\.com/[^}]*\}\}")


def replace_author(text, replacement):
    """Replace the whole \\author{...} block, matching nested braces."""
    i = text.index(r"\author{")
    j = i + len(r"\author{")
    depth = 1
    while depth:
        if text[j] == "{":
            depth += 1
        elif text[j] == "}":
            depth -= 1
        j += 1
    return text[:i] + replacement + text[j:]


def derive(src_text):
    out = src_text
    out = out.replace(r"\usepackage[final]{acl}", r"\usepackage[review]{acl}")
    if r"\usepackage[review]{acl}" not in out:
        sys.exit("main.tex does not use the ACL template as expected")
    out = replace_author(out, "\\author{Anonymous submission}")
    out = REPO_URL_RE.sub(r"\\footnote{" + ANON_FOOTNOTE + "}", out)
    if "Anonymous submission" not in out:
        sys.exit("author block not anonymized — check the \\author regex")
    if "github.com" in out:
        sys.exit("a de-anonymizing URL survived — check the footnote regex")
    banner = ("% ANONYMIZED REVIEW COPY - generated by "
              "scripts/make_submission.py.\n"
              "% DO NOT EDIT: edit paper/main.tex and regenerate.\n")
    return banner + out


def build(where):
    steps = [["pdflatex", "-interaction=nonstopmode", "main.tex"],
             ["bibtex", "main"],
             ["pdflatex", "-interaction=nonstopmode", "main.tex"],
             ["pdflatex", "-interaction=nonstopmode", "main.tex"]]
    for cmd in steps:
        r = subprocess.run(cmd, cwd=where, capture_output=True, text=True)
        if r.returncode != 0 and cmd[0] == "bibtex":
            print(f"  bibtex warned/failed:\n{r.stdout[-800:]}")
        elif r.returncode != 0:
            print(f"  {cmd[0]} failed:\n{r.stdout[-1500:]}")
            return False
    return True


def main():
    os.makedirs(SUB, exist_ok=True)
    src = open(os.path.join(PAPER, "main.tex"), encoding="utf-8").read()
    with open(os.path.join(SUB, "main.tex"), "w", encoding="utf-8") as f:
        f.write(derive(src))
    for name in ("acl.sty", "acl_natbib.bst", "references.bib"):
        shutil.copy2(os.path.join(PAPER, name), os.path.join(SUB, name))
    print(f"wrote {os.path.relpath(SUB, ROOT)}/"
          f"{{main.tex,acl.sty,acl_natbib.bst,references.bib}}")
    if "--no-build" in sys.argv:
        return
    if shutil.which("pdflatex") is None:
        print("pdflatex not found — skipped the build (upload paper/submission/"
              " to Overleaf)")
        return
    ok = build(SUB)
    pdf = os.path.join(SUB, "main.pdf")
    print(f"build {'OK' if ok else 'FAILED'}: {os.path.relpath(pdf, ROOT)}"
          f" ({os.path.getsize(pdf)/1e3:.0f} KB)" if os.path.exists(pdf)
          else "build produced no PDF")
    log = os.path.join(SUB, "main.log")
    if os.path.exists(log):
        pages = re.findall(r"Output written on main.pdf \((\d+) pages",
                           open(log, errors="ignore").read())
        if pages:
            print(f"pages: {pages[-1]}  (check the target workshop's limit; "
                  f"line numbers add ~1 page over the author copy)")


if __name__ == "__main__":
    main()
